site_name: NiPreps
site_description: Augmenting neuroimaging acquisition devices to produce analysis-grade data
site_author: The NiPreps developers
site_url: https://www.nipreps.org

# Repository
# repo_name: nipreps/nipreps.github.io
# repo_url: https://github.com/nipreps/nipreps.github.io

# Copyright
copyright: Copyright &copy; 2020

nav:
    - Home: index.md
    - BIDS-Apps:
      - Framework: apps/framework.md
      - Executing with Docker: apps/docker.md
      - Executing with Singularity: apps/singularity.md
    - Developers:
      - Contributing Guidelines: devs/guidelines.md
      - Versions Matrix: devs/versions.md
      - Releases: devs/releases.md
theme:
  name: material
  features:
    - tabs

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.snippets
  - markdown_include.include:
      base_path: docs

plugins:
  - toc-sidebar
