site_name: NiPreps
site_description: Augmenting neuroimaging acquisition devices to produce analysis-grade data
site_author: The NiPreps developers
site_url: https://www.nipreps.org
google_analytics: ['UA-170131052-1', 'www.nipreps.org']

# Repository
# repo_name: nipreps/nipreps.github.io
# repo_url: https://github.com/nipreps/nipreps.github.io

# Copyright
copyright: Copyright &copy; 2020

nav:
    - Home: index.md
    - NiPreps:
      - Framework: intro/nipreps.md
    - BIDS-Apps:
      - Introduction: apps/framework.md
      - Executing with Docker: apps/docker.md
      - Executing with Singularity: apps/singularity.md
    - Community:
      - Welcome: community/index.md
      - Membership: community/members.md
      - New features: community/features.md
      - Contributing: community/CONTRIBUTING.md
      - Code of Conduct: community/CODE_OF_CONDUCT.md
    - Developers:
      - Versions Matrix: devs/versions.md
      - Releases: devs/releases.md
theme:
  name: material
  features:
    - tabs

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.snippets
  - markdown_include.include:
      base_path: docs

plugins:
  - toc-sidebar
