version: 2.1

parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""
    
jobs:
  build:
    docker:
      - image: cimg/python:3.8.4
    steps:
      - checkout
      - run:
          name: Install requirements
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Build preview
          command: |
            . venv/bin/activate
            mkdocs build --site-dir _site_preview
      - store_artifacts:
          path: _site_preview
workflows:
  build:
    when: << pipeline.parameters.GHA_Action >>
    jobs:
      - build

