version: 2.1


    
jobs:
  build:
    docker:
      - image: cimg/python:3.8.4
    steps:
      - checkout
      - run:
          name: Install requirements
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Build preview
          command: |
            . venv/bin/activate
            mkdocs build --site-dir _site_preview
      - store_artifacts:
          path: _site_preview

workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 13 * * 6"
          filters:
            branches:
              only:
                - mkdocs
               
    jobs:
      - build
