version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8.2
    steps:
      - checkout
      - run:
          name: Install requirements
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Build preview
          command: |
            . venv/bin/activate
            mkdocs build --site-dir _site_preview
      - store_artifacts:
          path: _site_preview

